<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by TablePlus 2.10(268)
 * @author https://tableplus.com
 * @source https://github.com/TablePlus/tabledump
 */
class CreateMediaTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('master_medias', function (Blueprint $table) {
            $table->bigInteger('id')->unsigned()->autoIncrement();
            $table->string('model_type', 255);
            $table->bigInteger('model_id')->unsigned();
            $table->string('collection_name', 255)->nullable();
            $table->string('name', 255)->nullable();
            $table->string('file_name', 255)->nullable();
            $table->string('mime_type', 255)->nullable();
            $table->string('disk', 255)->nullable();
            $table->bigInteger('size')->unsigned()->nullable();
            $table->json('manipulations')->nullable();
            $table->json('custom_properties')->nullable();
            $table->json('responsive_images')->nullable();
            $table->integer('order_column')->unsigned()->nullable();
            $table->smallInteger('object_type')->default(0);
            $table->bigInteger('object_id')->default(0);
            $table->smallInteger('status')->nullable()->default(0);
            $table->integer('creator_id')->nullable()->default(0);
            $table->integer('editor_id')->nullable()->default(0);
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('medias');
    }
}
