<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by TablePlus 2.10(268)
 * @author https://tableplus.com
 * @source https://github.com/TablePlus/tabledump
 */
class CreateProductsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('products', function (Blueprint $table) {
            $table->bigInteger('id')->unsigned()->autoIncrement();
            $table->string('sku', 255)->nullable();
            $table->string('title', 255)->nullable();
            $table->integer('vendor_id')->nullable()->default(0)->index();
            $table->integer('category_id')->nullable()->default(0)->index();
            $table->text('summary')->nullable();
            $table->text('detail')->nullable();
            $table->integer('image_id')->nullable()->default(0);
            $table->string('image_url', 255)->nullable();
            $table->string('barcode', 255)->nullable();
            $table->decimal('price', 18, 2)->nullable()->default(0.00);
            $table->decimal('price_promotion', 18, 2)->nullable()->default(0.00);
            $table->integer('quantity')->default(1);
            $table->tinyInteger('is_home')->default(0)->index();
            $table->smallInteger('status')->nullable()->default(1)->index();
            $table->string('slug', 255)->nullable();
            $table->integer('views')->default(0);
            $table->string('tags', 255)->nullable();
            $table->string('seo_title', 255)->nullable();
            $table->string('seo_description', 255)->nullable();
            $table->timestamp('deleted_at')->nullable();
            $table->integer('creator_id')->nullable()->default(0);
            $table->integer('editor_id')->nullable()->default(0);
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('products');
    }
}
