<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by TablePlus 2.10(268)
 * @author https://tableplus.com
 * @source https://github.com/TablePlus/tabledump
 */
class CreateComment extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('web_comments', function (Blueprint $table) {
            $table->bigInteger('id')->unsigned()->autoIncrement();
            $table->bigInteger('post_id');
            $table->bigInteger('rating_id')->default(0);
            $table->string('author', 100)->nullable();
            $table->string('author_email', 100)->nullable();
            $table->string('author_url', 255)->nullable();
            $table->string('author_ip', 100)->nullable();
            $table->datetime('date')->nullable();
            $table->text('content')->nullable();
            $table->string('agent', 255)->nullable();
            $table->smallInteger('status')->nullable()->default(0);
            $table->smallInteger('type')->nullable()->default(0);
            $table->integer('parent')->nullable()->default(0);
            $table->integer('user_id')->nullable()->default(0);
            $table->integer('creator_id')->nullable()->default(0);
            $table->integer('editor_id')->nullable()->default(0);
            $table->timestamp('deleted_at')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('comments');
    }
}
