<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by TablePlus 2.10(268)
 * @author https://tableplus.com
 * @source https://github.com/TablePlus/tabledump
 */
class CreateTableAds extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('web_ads', function (Blueprint $table) {
            $table->bigInteger('id')->unsigned()->autoIncrement();
            $table->string('position', 255)->nullable();
            $table->string('title', 255)->nullable();
            $table->string('link', 255)->nullable();
            $table->smallInteger('type')->nullable()->default(0);
            $table->string('theme', 50)->nullable()->default(0);
            $table->text('code')->nullable();
            $table->integer('views')->nullable()->default(0);
            $table->integer('image_id')->nullable()->default(0);
            $table->string('image_url', 255)->nullable();
            $table->smallInteger('status')->nullable()->default(1);
            $table->integer('order_by')->nullable()->default(0);
            $table->integer('creator_id')->nullable()->default(0);
            $table->integer('editor_id')->nullable()->default(0);
            $table->timestamp('deleted_at')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('ads');
    }
}
